// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connect.proto

#ifndef PROTOBUF_INCLUDED_connect_2eproto
#define PROTOBUF_INCLUDED_connect_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_connect_2eproto 

namespace protobuf_connect_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_connect_2eproto
namespace gamemessages {
class Connect;
class ConnectDefaultTypeInternal;
extern ConnectDefaultTypeInternal _Connect_default_instance_;
}  // namespace gamemessages
namespace google {
namespace protobuf {
template<> ::gamemessages::Connect* Arena::CreateMaybeMessage<::gamemessages::Connect>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace gamemessages {

// ===================================================================

class Connect : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gamemessages.Connect) */ {
 public:
  Connect();
  virtual ~Connect();

  Connect(const Connect& from);

  inline Connect& operator=(const Connect& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Connect(Connect&& from) noexcept
    : Connect() {
    *this = ::std::move(from);
  }

  inline Connect& operator=(Connect&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Connect& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Connect* internal_default_instance() {
    return reinterpret_cast<const Connect*>(
               &_Connect_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Connect* other);
  friend void swap(Connect& a, Connect& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Connect* New() const final {
    return CreateMaybeMessage<Connect>(NULL);
  }

  Connect* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Connect>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Connect& from);
  void MergeFrom(const Connect& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Connect* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string gameToken = 1;
  bool has_gametoken() const;
  void clear_gametoken();
  static const int kGameTokenFieldNumber = 1;
  const ::std::string& gametoken() const;
  void set_gametoken(const ::std::string& value);
  #if LANG_CXX11
  void set_gametoken(::std::string&& value);
  #endif
  void set_gametoken(const char* value);
  void set_gametoken(const char* value, size_t size);
  ::std::string* mutable_gametoken();
  ::std::string* release_gametoken();
  void set_allocated_gametoken(::std::string* gametoken);

  // @@protoc_insertion_point(class_scope:gamemessages.Connect)
 private:
  void set_has_gametoken();
  void clear_has_gametoken();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr gametoken_;
  friend struct ::protobuf_connect_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Connect

// required string gameToken = 1;
inline bool Connect::has_gametoken() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Connect::set_has_gametoken() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Connect::clear_has_gametoken() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Connect::clear_gametoken() {
  gametoken_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_gametoken();
}
inline const ::std::string& Connect::gametoken() const {
  // @@protoc_insertion_point(field_get:gamemessages.Connect.gameToken)
  return gametoken_.GetNoArena();
}
inline void Connect::set_gametoken(const ::std::string& value) {
  set_has_gametoken();
  gametoken_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gamemessages.Connect.gameToken)
}
#if LANG_CXX11
inline void Connect::set_gametoken(::std::string&& value) {
  set_has_gametoken();
  gametoken_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gamemessages.Connect.gameToken)
}
#endif
inline void Connect::set_gametoken(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_gametoken();
  gametoken_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gamemessages.Connect.gameToken)
}
inline void Connect::set_gametoken(const char* value, size_t size) {
  set_has_gametoken();
  gametoken_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gamemessages.Connect.gameToken)
}
inline ::std::string* Connect::mutable_gametoken() {
  set_has_gametoken();
  // @@protoc_insertion_point(field_mutable:gamemessages.Connect.gameToken)
  return gametoken_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Connect::release_gametoken() {
  // @@protoc_insertion_point(field_release:gamemessages.Connect.gameToken)
  if (!has_gametoken()) {
    return NULL;
  }
  clear_has_gametoken();
  return gametoken_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Connect::set_allocated_gametoken(::std::string* gametoken) {
  if (gametoken != NULL) {
    set_has_gametoken();
  } else {
    clear_has_gametoken();
  }
  gametoken_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), gametoken);
  // @@protoc_insertion_point(field_set_allocated:gamemessages.Connect.gameToken)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace gamemessages

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_connect_2eproto
